### ISSUE TITLE
schema.org type Organization for geodex.org

### ISSUE THREAD

**Issue by fils** [earthcubearchitecture-project418/webui#3]
@ashepherd 

So..  it might a bit embarrassing if in all this we failed to make a type Org entry in the index file for geodex.org  :)

Could you edit the /static/html/index.html  file to have an entry for us sometime!
We can have it point to the swagger doc...  http://geodex.org/apidocs.json and also to the datasets (later) that we build up.

Thanks

**Comment by ashepherd** [comment]
fixed in  commit a2b33bf0ca3811ec251019dd89abd3e946a443a8
