### ISSUE TITLE
request for comment on prov in schema.org

### ISSUE THREAD

**Issue by fils** [earthcubearchitecture-project418/webui#4]
@ashepherd 
Could you look over 
/static/datafiles/p418graph/schemaorg.json

I am working on an approach where we put PROV-AQ patterns and info into the schema.org.  I'm curious if this would be another path to PROV-AQ information that would not require request / response header re-writing (injection).   

How would you see the prov namespace being used in a JSON-LD package?  Do we need a better syntax?   Looking over resources like [1] and the Note in general I am not sure if we need to scope these in a type, or if it's ok to let them attach to type Dataset..  (perhaps type DCAT dataset or something?)    Can we avoid additional type here..  or is this a case where it's  useful?

[1] https://www.w3.org/TR/2013/NOTE-prov-aq-20130430/#resource-represented-as-html

**Comment by ashepherd** [comment]
That PROV looks great! I think the Google Testing tool needs to improve to make it look like it's not errors to use other vocabs. Unless you wanted to force PROV to be aligned with schema.org classes, then we could make attempts to do what we did for P418, but I don't think you should have to

**Comment by fils** [comment]
Great..  thanks for looking that over!
Now I just need to get all the URLs and software working in a week  :)   

I don't think for now we need to align with scheme.org classes (what classes would it align too?)
I think it's almost valid for prov to attach to THING so this should be fine ... 

If you don't have any other comments for now feel free to close this issue!

**Comment by ashepherd** [comment]
yeah, picking schema.org classes would be hard b/c of the disjointness in PROV.
